connector.name=mayapostgres

redis-url=redis://redis:6379

keywords=

number_of_worker_threads=5

run_in_coordinator_only=true

worker_index_to_run_in=1

pg-connection-url=jdbc:postgresql://10.20.4.31:31953/services

pg-connection-user=postgres_viewer

pg-connection-password=XnoO@0rNP^